# This file is used if we only want a container with a db, no network. .env DB_HOST should be localhost.

services:
    db:
        build:
            context: ./
            dockerfile: ./Dockerfile.db
        restart: always
        user: postgres
        volumes:
            - db-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - ${DB_PORT}:${DB_PORT}
        healthcheck:
            test: ['CMD', 'pg_isready']
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    db-data:
