# For now, db is on server. If project had more traffic, would want to move db out into managed db solution and not on same server as backend.
services:
    backend:
        image: jamesathanasiou/tracker:latest
        depends_on:
            - db
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        restart: unless-stopped
        expose:
            - ${APP_PORT}
        ports:
            - ${APP_PORT}:${APP_PORT}
        env_file: ".env"
        command: yarn start
    db:
        build:
            context: ./
            dockerfile: ./Dockerfile.db
        restart: always
        user: postgres
        volumes:
            - db-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - ${DB_PORT}:${DB_PORT}
        healthcheck:
            test: ['CMD', 'pg_isready']
            interval: 10s
            timeout: 5s
            retries: 5
    db-migration:
        image: jamesathanasiou/tracker:latest
        depends_on:
            db:
                condition: service_healthy
        env_file: ".env"
        command: yarn migrate

volumes:
    db-data:
