import {
    ColumnType,
    Generated,
    Insertable,
    Selectable,
    Updateable,
  } from 'kysely'
  
  // defines db structure

  /* 
  From docs:
  For production apps, it is recommended to automatically generate your Database interface by introspecting your production database or Prisma schemas. Generated types might differ in naming convention, internal order, etc. Find out more at "Generating types".
  */
  export interface Database {
    person: PersonTable
    pet: PetTable
  }

  export interface PersonTable {
    // JTODO not sure what this means
    // Columns that are generated by the database should be marked
    // using the `Generated` type. This way they are automatically
    // made optional in inserts and updates.
    id: Generated<number>
  
    first_name: string
    gender: 'man' | 'woman' | 'other'
    // optional field.
    last_name: string | null

    created_at: ColumnType<Date, string | undefined, never>
    updated_at: ColumnType<Date, string | undefined, string | undefined>
  }
  
  // use wrappers to set types
  export type Person = Selectable<PersonTable>
  export type NewPerson = Insertable<PersonTable>
  export type PersonUpdate = Updateable<PersonTable>
  
  export interface PetTable {
    id: Generated<number>
    name: string
    owner_id: number
    species: 'dog' | 'cat'
  }
  
  export type Pet = Selectable<PetTable>
  export type NewPet = Insertable<PetTable>
  export type PetUpdate = Updateable<PetTable>